#!/bin/bash
# Script para verificar el estado de Data Guard Broker y Fast-Start Failover

echo "=== Estado de Data Guard Broker ==="

dgmgrl sys/$ORACLE_SID-$ORACLE_STANDBY_SID-1@$ORACLE_SID <<EOF
SHOW CONFIGURATION;
SHOW DATABASE $ORACLE_SID;
SHOW DATABASE $ORACLE_STANDBY_SID;
SHOW FAST_START FAILOVER;
EOF

echo ""
echo "=== Estado de sincronización ==="
sqlplus sys/$ORACLE_SID-$ORACLE_STANDBY_SID-1@$ORACLE_SID AS SYSDBA <<EOF
SELECT DEST_ID, STATUS, ERROR FROM V\$ARCHIVE_DEST WHERE DEST_ID IN (1,2);
SELECT SEQUENCE#, APPLIED FROM V\$ARCHIVED_LOG WHERE DEST_ID=2 ORDER BY SEQUENCE# DESC FETCH FIRST 5 ROWS ONLY;
EXIT;
EOF