-- =====================================================
-- VITALIS DATABASE SCHEMA CREATION SCRIPT
-- Schema: VITALIS_SCHEMA
-- Password: VITALIS
-- Created: October 26, 2025
-- Description: Primary schema creation script for Vitalis DB
-- =====================================================
-- Create user/schema VITALIS_SCHEMA
CREATE USER VITALIS_SCHEMA IDENTIFIED BY VITALIS
DEFAULT TABLESPACE VITALIS_DATA
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON VITALIS_DATA
QUOTA UNLIMITED ON VITALIS_IDX;

-- Grant basic privileges to VITALIS_SCHEMA
GRANT CONNECT TO VITALIS_SCHEMA;
GRANT RESOURCE TO VITALIS_SCHEMA;
GRANT CREATE SESSION TO VITALIS_SCHEMA;
GRANT CREATE TABLE TO VITALIS_SCHEMA;
GRANT CREATE VIEW TO VITALIS_SCHEMA;
GRANT CREATE SEQUENCE TO VITALIS_SCHEMA;
GRANT CREATE PROCEDURE TO VITALIS_SCHEMA;
GRANT CREATE TRIGGER TO VITALIS_SCHEMA;
GRANT ALTER SESSION TO VITALIS_SCHEMA;
GRANT UNLIMITED TABLESPACE TO VITALIS_SCHEMA;
GRANT DEBUG CONNECT SESSION TO VITALIS_SCHEMA;
GRANT DEBUG ANY PROCEDURE TO VITALIS_SCHEMA;

-- Schema successfully created
SELECT 'VITALIS_SCHEMA created successfully' AS status FROM dual;