-- =====================================================
-- VITALIS DATABASE SCHEMA CREATION SCRIPT
-- Schema: VITALIS_SCHEMA
-- Password: VITALIS
-- Created: October 26, 2025
-- Description: Primary schema creation script for Vitalis DB
-- =====================================================
-- Create user/schema VITALIS_SCHEMA
CREATE USER VITALIS_SCHEMA IDENTIFIED BY VITALIS
DEFAULT TABLESPACE VITALIS_DATA
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON VITALIS_DATA
QUOTA UNLIMITED ON VITALIS_IDX;

-- Grant basic privileges to VITALIS_SCHEMA
GRANT CONNECT TO VITALIS_SCHEMA;
GRANT RESOURCE TO VITALIS_SCHEMA;
GRANT CREATE SESSION TO VITALIS_SCHEMA;
GRANT CREATE TABLE TO VITALIS_SCHEMA;
GRANT CREATE VIEW TO VITALIS_SCHEMA;
GRANT CREATE SEQUENCE TO VITALIS_SCHEMA;
GRANT CREATE PROCEDURE TO VITALIS_SCHEMA;
GRANT CREATE TRIGGER TO VITALIS_SCHEMA;
GRANT ALTER SESSION TO VITALIS_SCHEMA;
GRANT UNLIMITED TABLESPACE TO VITALIS_SCHEMA;

---Permissions for procedures and packages

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO VITALIS_SCHEMA;
GRANT EXECUTE ON SYS.UTL_SMTP TO VITALIS_SCHEMA;
GRANT EXECUTE ON SYS.UTL_TCP TO VITALIS_SCHEMA;
GRANT EXECUTE ON SYS.UTL_ENCODE TO VITALIS_SCHEMA;
GRANT CREATE JOB TO VITALIS_SCHEMA;
GRANT MANAGE SCHEDULER TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_TABLESPACE_USAGE_METRICS TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_OBJECTS TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_INDEXES TO VITALIS_SCHEMA;
GRANT CONNECT, RESOURCE TO VITALIS_SCHEMA;
GRANT CREATE VIEW, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO VITALIS_SCHEMA;
GRANT UNLIMITED TABLESPACE TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_DATA_FILES TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_FREE_SPACE TO VITALIS_SCHEMA;
GRANT SELECT ON DBA_TABLESPACES TO VITALIS_SCHEMA;
GRANT SELECT ANY DICTIONARY TO VITALIS_SCHEMA;

GRANT CREATE EXTERNAL JOB TO VITALIS_SCHEMA;
GRANT EXECUTE ON DBMS_SCHEDULER TO VITALIS_SCHEMA;

-- Schema successfully created
SELECT 'VITALIS_SCHEMA created successfully' AS status FROM dual;