CREATE BIGFILE TABLESPACE VITALIS_DATA
  DATAFILE SIZE 500M
  AUTOEXTEND ON NEXT 100M MAXSIZE 10G
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE VITALIS_IDX
  DATAFILE SIZE 200M
  AUTOEXTEND ON NEXT 100M MAXSIZE 5G
  SEGMENT SPACE MANAGEMENT AUTO;
