-- Eliminar tablespaces si existen (ignora errores si no existen)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLESPACE VITALIS_DATA INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -959 THEN -- ORA-00959: tablespace does not exist
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLESPACE VITALIS_IDX INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -959 THEN -- ORA-00959: tablespace does not exist
         RAISE;
      END IF;
END;
/

-- Crear tablespaces
CREATE TABLESPACE VITALIS_DATA
  DATAFILE '/opt/oracle/oradata/VITALIS/VITALISPDB1/vitalis_data01.dbf' 
  SIZE 500M
  AUTOEXTEND ON NEXT 100M MAXSIZE 10G
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE VITALIS_IDX
  DATAFILE '/opt/oracle/oradata/VITALIS/VITALISPDB1/vitalis_idx01.dbf' 
  SIZE 200M
  AUTOEXTEND ON NEXT 100M MAXSIZE 5G
  SEGMENT SPACE MANAGEMENT AUTO;
